package com.konfigthis.client;

import com.konfigthis.client.api.ApiInformationEssentialsApi;
import com.konfigthis.client.api.AuthenticationExtrasAuthenticateApi;
import com.konfigthis.client.api.AuthenticationExtrasConvertApi;
import com.konfigthis.client.api.AuthenticationExtrasEssentialsApi;
import com.konfigthis.client.api.AuthenticationExtrasExchangeApi;
import com.konfigthis.client.api.CategoriesChannelsApi;
import com.konfigthis.client.api.CategoriesEssentialsApi;
import com.konfigthis.client.api.CategoriesGroupsApi;
import com.konfigthis.client.api.CategoriesUsersApi;
import com.konfigthis.client.api.CategoriesVideosApi;
import com.konfigthis.client.api.ChannelsCategoriesApi;
import com.konfigthis.client.api.ChannelsEssentialsApi;
import com.konfigthis.client.api.ChannelsModeratorsApi;
import com.konfigthis.client.api.ChannelsPrivateChannelMembersApi;
import com.konfigthis.client.api.ChannelsSubscriptionsAndSubscribersApi;
import com.konfigthis.client.api.ChannelsTagsApi;
import com.konfigthis.client.api.ChannelsVideosApi;
import com.konfigthis.client.api.EmbedPresetsCustomLogosApi;
import com.konfigthis.client.api.EmbedPresetsEssentialsApi;
import com.konfigthis.client.api.EmbedPresetsTimelineEventsApi;
import com.konfigthis.client.api.EmbedPresetsVideosApi;
import com.konfigthis.client.api.FoldersEssentialsApi;
import com.konfigthis.client.api.FoldersItemsApi;
import com.konfigthis.client.api.FoldersVideosApi;
import com.konfigthis.client.api.GroupsEssentialsApi;
import com.konfigthis.client.api.GroupsSubscriptionsApi;
import com.konfigthis.client.api.GroupsUsersApi;
import com.konfigthis.client.api.GroupsVideosApi;
import com.konfigthis.client.api.LikesEssentialsApi;
import com.konfigthis.client.api.LiveEmbedPrivacyApi;
import com.konfigthis.client.api.LiveEssentialsApi;
import com.konfigthis.client.api.LiveEventM3U8PlaybackApi;
import com.konfigthis.client.api.LiveEventActivationApi;
import com.konfigthis.client.api.LiveEventAutomatedClosedCaptionsApi;
import com.konfigthis.client.api.LiveEventDestinationsApi;
import com.konfigthis.client.api.LiveEventEndApi;
import com.konfigthis.client.api.LiveEventLowLatencyApi;
import com.konfigthis.client.api.LiveEventSessionsApi;
import com.konfigthis.client.api.LiveEventThumbnailsApi;
import com.konfigthis.client.api.LiveEventVideosApi;
import com.konfigthis.client.api.OnDemandBackgroundsApi;
import com.konfigthis.client.api.OnDemandEssentialsApi;
import com.konfigthis.client.api.OnDemandGenresApi;
import com.konfigthis.client.api.OnDemandPostersApi;
import com.konfigthis.client.api.OnDemandPromotionsApi;
import com.konfigthis.client.api.OnDemandPurchasesAndRentalsApi;
import com.konfigthis.client.api.OnDemandRegionsApi;
import com.konfigthis.client.api.OnDemandSeasonsApi;
import com.konfigthis.client.api.OnDemandVideosApi;
import com.konfigthis.client.api.PaymentsEssentialsApi;
import com.konfigthis.client.api.PortfoliosEssentialsApi;
import com.konfigthis.client.api.PortfoliosVideosApi;
import com.konfigthis.client.api.ShowcasesCustomShowcaseLogosApi;
import com.konfigthis.client.api.ShowcasesCustomShowcaseThumbnailsApi;
import com.konfigthis.client.api.ShowcasesEssentialsApi;
import com.konfigthis.client.api.ShowcasesShowcaseVideosApi;
import com.konfigthis.client.api.SubscriptionPlansEssentialsApi;
import com.konfigthis.client.api.TagsEssentialsApi;
import com.konfigthis.client.api.TeamsMembersApi;
import com.konfigthis.client.api.TutorialEssentialsApi;
import com.konfigthis.client.api.UsersAnalyticsApi;
import com.konfigthis.client.api.UsersEssentialsApi;
import com.konfigthis.client.api.UsersFeedsApi;
import com.konfigthis.client.api.UsersFollowersApi;
import com.konfigthis.client.api.UsersPicturesApi;
import com.konfigthis.client.api.UsersSearchApi;
import com.konfigthis.client.api.UsersWatchHistoryApi;
import com.konfigthis.client.api.VideosAnimatedThumbnailsApi;
import com.konfigthis.client.api.VideosChaptersApi;
import com.konfigthis.client.api.VideosContentRatingsApi;
import com.konfigthis.client.api.VideosCreativeCommonsApi;
import com.konfigthis.client.api.VideosCreditsApi;
import com.konfigthis.client.api.VideosEmbedPrivacyApi;
import com.konfigthis.client.api.VideosEssentialsApi;
import com.konfigthis.client.api.VideosFragmentsApi;
import com.konfigthis.client.api.VideosLanguagesApi;
import com.konfigthis.client.api.VideosLiveM3U8PlaybackApi;
import com.konfigthis.client.api.VideosNondestructiveTrimmingApi;
import com.konfigthis.client.api.VideosRecommendationsApi;
import com.konfigthis.client.api.VideosShowcasesApi;
import com.konfigthis.client.api.VideosTagsApi;
import com.konfigthis.client.api.VideosTextTracksApi;
import com.konfigthis.client.api.VideosThumbnailsApi;
import com.konfigthis.client.api.VideosTranscriptsApi;
import com.konfigthis.client.api.VideosUnlistedVideosApi;
import com.konfigthis.client.api.VideosUploadsApi;
import com.konfigthis.client.api.VideosVersionsApi;
import com.konfigthis.client.api.VideosVideoCommentsApi;
import com.konfigthis.client.api.WatchLaterQueueEssentialsApi;
import com.konfigthis.client.api.WebinarEmailsApi;
import com.konfigthis.client.api.WebinarEssentialsApi;
import com.konfigthis.client.api.WebinarRegistrationsApi;

public class Vimeo {
    private ApiClient apiClient;
    public final ApiInformationEssentialsApi apiInformationEssentials;
    public final AuthenticationExtrasAuthenticateApi authenticationExtrasAuthenticate;
    public final AuthenticationExtrasConvertApi authenticationExtrasConvert;
    public final AuthenticationExtrasEssentialsApi authenticationExtrasEssentials;
    public final AuthenticationExtrasExchangeApi authenticationExtrasExchange;
    public final CategoriesChannelsApi categoriesChannels;
    public final CategoriesEssentialsApi categoriesEssentials;
    public final CategoriesGroupsApi categoriesGroups;
    public final CategoriesUsersApi categoriesUsers;
    public final CategoriesVideosApi categoriesVideos;
    public final ChannelsCategoriesApi channelsCategories;
    public final ChannelsEssentialsApi channelsEssentials;
    public final ChannelsModeratorsApi channelsModerators;
    public final ChannelsPrivateChannelMembersApi channelsPrivateChannelMembers;
    public final ChannelsSubscriptionsAndSubscribersApi channelsSubscriptionsAndSubscribers;
    public final ChannelsTagsApi channelsTags;
    public final ChannelsVideosApi channelsVideos;
    public final EmbedPresetsCustomLogosApi embedPresetsCustomLogos;
    public final EmbedPresetsEssentialsApi embedPresetsEssentials;
    public final EmbedPresetsTimelineEventsApi embedPresetsTimelineEvents;
    public final EmbedPresetsVideosApi embedPresetsVideos;
    public final FoldersEssentialsApi foldersEssentials;
    public final FoldersItemsApi foldersItems;
    public final FoldersVideosApi foldersVideos;
    public final GroupsEssentialsApi groupsEssentials;
    public final GroupsSubscriptionsApi groupsSubscriptions;
    public final GroupsUsersApi groupsUsers;
    public final GroupsVideosApi groupsVideos;
    public final LikesEssentialsApi likesEssentials;
    public final LiveEmbedPrivacyApi liveEmbedPrivacy;
    public final LiveEssentialsApi liveEssentials;
    public final LiveEventM3U8PlaybackApi liveEventM3U8Playback;
    public final LiveEventActivationApi liveEventActivation;
    public final LiveEventAutomatedClosedCaptionsApi liveEventAutomatedClosedCaptions;
    public final LiveEventDestinationsApi liveEventDestinations;
    public final LiveEventEndApi liveEventEnd;
    public final LiveEventLowLatencyApi liveEventLowLatency;
    public final LiveEventSessionsApi liveEventSessions;
    public final LiveEventThumbnailsApi liveEventThumbnails;
    public final LiveEventVideosApi liveEventVideos;
    public final OnDemandBackgroundsApi onDemandBackgrounds;
    public final OnDemandEssentialsApi onDemandEssentials;
    public final OnDemandGenresApi onDemandGenres;
    public final OnDemandPostersApi onDemandPosters;
    public final OnDemandPromotionsApi onDemandPromotions;
    public final OnDemandPurchasesAndRentalsApi onDemandPurchasesAndRentals;
    public final OnDemandRegionsApi onDemandRegions;
    public final OnDemandSeasonsApi onDemandSeasons;
    public final OnDemandVideosApi onDemandVideos;
    public final PaymentsEssentialsApi paymentsEssentials;
    public final PortfoliosEssentialsApi portfoliosEssentials;
    public final PortfoliosVideosApi portfoliosVideos;
    public final ShowcasesCustomShowcaseLogosApi showcasesCustomShowcaseLogos;
    public final ShowcasesCustomShowcaseThumbnailsApi showcasesCustomShowcaseThumbnails;
    public final ShowcasesEssentialsApi showcasesEssentials;
    public final ShowcasesShowcaseVideosApi showcasesShowcaseVideos;
    public final SubscriptionPlansEssentialsApi subscriptionPlansEssentials;
    public final TagsEssentialsApi tagsEssentials;
    public final TeamsMembersApi teamsMembers;
    public final TutorialEssentialsApi tutorialEssentials;
    public final UsersAnalyticsApi usersAnalytics;
    public final UsersEssentialsApi usersEssentials;
    public final UsersFeedsApi usersFeeds;
    public final UsersFollowersApi usersFollowers;
    public final UsersPicturesApi usersPictures;
    public final UsersSearchApi usersSearch;
    public final UsersWatchHistoryApi usersWatchHistory;
    public final VideosAnimatedThumbnailsApi videosAnimatedThumbnails;
    public final VideosChaptersApi videosChapters;
    public final VideosContentRatingsApi videosContentRatings;
    public final VideosCreativeCommonsApi videosCreativeCommons;
    public final VideosCreditsApi videosCredits;
    public final VideosEmbedPrivacyApi videosEmbedPrivacy;
    public final VideosEssentialsApi videosEssentials;
    public final VideosFragmentsApi videosFragments;
    public final VideosLanguagesApi videosLanguages;
    public final VideosLiveM3U8PlaybackApi videosLiveM3U8Playback;
    public final VideosNondestructiveTrimmingApi videosNondestructiveTrimming;
    public final VideosRecommendationsApi videosRecommendations;
    public final VideosShowcasesApi videosShowcases;
    public final VideosTagsApi videosTags;
    public final VideosTextTracksApi videosTextTracks;
    public final VideosThumbnailsApi videosThumbnails;
    public final VideosTranscriptsApi videosTranscripts;
    public final VideosUnlistedVideosApi videosUnlistedVideos;
    public final VideosUploadsApi videosUploads;
    public final VideosVersionsApi videosVersions;
    public final VideosVideoCommentsApi videosVideoComments;
    public final WatchLaterQueueEssentialsApi watchLaterQueueEssentials;
    public final WebinarEmailsApi webinarEmails;
    public final WebinarEssentialsApi webinarEssentials;
    public final WebinarRegistrationsApi webinarRegistrations;

    public Vimeo() {
        this(null);
    }

    public Vimeo(Configuration configuration) {
        this.apiClient = new ApiClient(null, configuration);
        this.apiInformationEssentials = new ApiInformationEssentialsApi(this.apiClient);
        this.authenticationExtrasAuthenticate = new AuthenticationExtrasAuthenticateApi(this.apiClient);
        this.authenticationExtrasConvert = new AuthenticationExtrasConvertApi(this.apiClient);
        this.authenticationExtrasEssentials = new AuthenticationExtrasEssentialsApi(this.apiClient);
        this.authenticationExtrasExchange = new AuthenticationExtrasExchangeApi(this.apiClient);
        this.categoriesChannels = new CategoriesChannelsApi(this.apiClient);
        this.categoriesEssentials = new CategoriesEssentialsApi(this.apiClient);
        this.categoriesGroups = new CategoriesGroupsApi(this.apiClient);
        this.categoriesUsers = new CategoriesUsersApi(this.apiClient);
        this.categoriesVideos = new CategoriesVideosApi(this.apiClient);
        this.channelsCategories = new ChannelsCategoriesApi(this.apiClient);
        this.channelsEssentials = new ChannelsEssentialsApi(this.apiClient);
        this.channelsModerators = new ChannelsModeratorsApi(this.apiClient);
        this.channelsPrivateChannelMembers = new ChannelsPrivateChannelMembersApi(this.apiClient);
        this.channelsSubscriptionsAndSubscribers = new ChannelsSubscriptionsAndSubscribersApi(this.apiClient);
        this.channelsTags = new ChannelsTagsApi(this.apiClient);
        this.channelsVideos = new ChannelsVideosApi(this.apiClient);
        this.embedPresetsCustomLogos = new EmbedPresetsCustomLogosApi(this.apiClient);
        this.embedPresetsEssentials = new EmbedPresetsEssentialsApi(this.apiClient);
        this.embedPresetsTimelineEvents = new EmbedPresetsTimelineEventsApi(this.apiClient);
        this.embedPresetsVideos = new EmbedPresetsVideosApi(this.apiClient);
        this.foldersEssentials = new FoldersEssentialsApi(this.apiClient);
        this.foldersItems = new FoldersItemsApi(this.apiClient);
        this.foldersVideos = new FoldersVideosApi(this.apiClient);
        this.groupsEssentials = new GroupsEssentialsApi(this.apiClient);
        this.groupsSubscriptions = new GroupsSubscriptionsApi(this.apiClient);
        this.groupsUsers = new GroupsUsersApi(this.apiClient);
        this.groupsVideos = new GroupsVideosApi(this.apiClient);
        this.likesEssentials = new LikesEssentialsApi(this.apiClient);
        this.liveEmbedPrivacy = new LiveEmbedPrivacyApi(this.apiClient);
        this.liveEssentials = new LiveEssentialsApi(this.apiClient);
        this.liveEventM3U8Playback = new LiveEventM3U8PlaybackApi(this.apiClient);
        this.liveEventActivation = new LiveEventActivationApi(this.apiClient);
        this.liveEventAutomatedClosedCaptions = new LiveEventAutomatedClosedCaptionsApi(this.apiClient);
        this.liveEventDestinations = new LiveEventDestinationsApi(this.apiClient);
        this.liveEventEnd = new LiveEventEndApi(this.apiClient);
        this.liveEventLowLatency = new LiveEventLowLatencyApi(this.apiClient);
        this.liveEventSessions = new LiveEventSessionsApi(this.apiClient);
        this.liveEventThumbnails = new LiveEventThumbnailsApi(this.apiClient);
        this.liveEventVideos = new LiveEventVideosApi(this.apiClient);
        this.onDemandBackgrounds = new OnDemandBackgroundsApi(this.apiClient);
        this.onDemandEssentials = new OnDemandEssentialsApi(this.apiClient);
        this.onDemandGenres = new OnDemandGenresApi(this.apiClient);
        this.onDemandPosters = new OnDemandPostersApi(this.apiClient);
        this.onDemandPromotions = new OnDemandPromotionsApi(this.apiClient);
        this.onDemandPurchasesAndRentals = new OnDemandPurchasesAndRentalsApi(this.apiClient);
        this.onDemandRegions = new OnDemandRegionsApi(this.apiClient);
        this.onDemandSeasons = new OnDemandSeasonsApi(this.apiClient);
        this.onDemandVideos = new OnDemandVideosApi(this.apiClient);
        this.paymentsEssentials = new PaymentsEssentialsApi(this.apiClient);
        this.portfoliosEssentials = new PortfoliosEssentialsApi(this.apiClient);
        this.portfoliosVideos = new PortfoliosVideosApi(this.apiClient);
        this.showcasesCustomShowcaseLogos = new ShowcasesCustomShowcaseLogosApi(this.apiClient);
        this.showcasesCustomShowcaseThumbnails = new ShowcasesCustomShowcaseThumbnailsApi(this.apiClient);
        this.showcasesEssentials = new ShowcasesEssentialsApi(this.apiClient);
        this.showcasesShowcaseVideos = new ShowcasesShowcaseVideosApi(this.apiClient);
        this.subscriptionPlansEssentials = new SubscriptionPlansEssentialsApi(this.apiClient);
        this.tagsEssentials = new TagsEssentialsApi(this.apiClient);
        this.teamsMembers = new TeamsMembersApi(this.apiClient);
        this.tutorialEssentials = new TutorialEssentialsApi(this.apiClient);
        this.usersAnalytics = new UsersAnalyticsApi(this.apiClient);
        this.usersEssentials = new UsersEssentialsApi(this.apiClient);
        this.usersFeeds = new UsersFeedsApi(this.apiClient);
        this.usersFollowers = new UsersFollowersApi(this.apiClient);
        this.usersPictures = new UsersPicturesApi(this.apiClient);
        this.usersSearch = new UsersSearchApi(this.apiClient);
        this.usersWatchHistory = new UsersWatchHistoryApi(this.apiClient);
        this.videosAnimatedThumbnails = new VideosAnimatedThumbnailsApi(this.apiClient);
        this.videosChapters = new VideosChaptersApi(this.apiClient);
        this.videosContentRatings = new VideosContentRatingsApi(this.apiClient);
        this.videosCreativeCommons = new VideosCreativeCommonsApi(this.apiClient);
        this.videosCredits = new VideosCreditsApi(this.apiClient);
        this.videosEmbedPrivacy = new VideosEmbedPrivacyApi(this.apiClient);
        this.videosEssentials = new VideosEssentialsApi(this.apiClient);
        this.videosFragments = new VideosFragmentsApi(this.apiClient);
        this.videosLanguages = new VideosLanguagesApi(this.apiClient);
        this.videosLiveM3U8Playback = new VideosLiveM3U8PlaybackApi(this.apiClient);
        this.videosNondestructiveTrimming = new VideosNondestructiveTrimmingApi(this.apiClient);
        this.videosRecommendations = new VideosRecommendationsApi(this.apiClient);
        this.videosShowcases = new VideosShowcasesApi(this.apiClient);
        this.videosTags = new VideosTagsApi(this.apiClient);
        this.videosTextTracks = new VideosTextTracksApi(this.apiClient);
        this.videosThumbnails = new VideosThumbnailsApi(this.apiClient);
        this.videosTranscripts = new VideosTranscriptsApi(this.apiClient);
        this.videosUnlistedVideos = new VideosUnlistedVideosApi(this.apiClient);
        this.videosUploads = new VideosUploadsApi(this.apiClient);
        this.videosVersions = new VideosVersionsApi(this.apiClient);
        this.videosVideoComments = new VideosVideoCommentsApi(this.apiClient);
        this.watchLaterQueueEssentials = new WatchLaterQueueEssentialsApi(this.apiClient);
        this.webinarEmails = new WebinarEmailsApi(this.apiClient);
        this.webinarEssentials = new WebinarEssentialsApi(this.apiClient);
        this.webinarRegistrations = new WebinarRegistrationsApi(this.apiClient);
    }

}
