/*
 * Vimeo API
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CreateWebinarRequestEmailSettings;
import com.konfigthis.client.model.CreateWebinarRequestPrivacy;
import com.konfigthis.client.model.CreateWebinarRequestSchedule;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateWebinarRequest
 */
public class CreateWebinarRequestTest {
    private final CreateWebinarRequest model = new CreateWebinarRequest();

    /**
     * Model tests for CreateWebinarRequest
     */
    @Test
    public void testCreateWebinarRequest() {
        // TODO: test CreateWebinarRequest
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'emailSettings'
     */
    @Test
    public void emailSettingsTest() {
        // TODO: test emailSettings
    }

    /**
     * Test the property 'folderUri'
     */
    @Test
    public void folderUriTest() {
        // TODO: test folderUri
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'privacy'
     */
    @Test
    public void privacyTest() {
        // TODO: test privacy
    }

    /**
     * Test the property 'schedule'
     */
    @Test
    public void scheduleTest() {
        // TODO: test schedule
    }

    /**
     * Test the property 'timeZone'
     */
    @Test
    public void timeZoneTest() {
        // TODO: test timeZone
    }

}
