/*
 * Vimeo API
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LiveEventVideosAddMultipleVideosRequestVideosInnerVideo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LiveEventVideosAddMultipleVideosRequestVideosInner
 */
public class LiveEventVideosAddMultipleVideosRequestVideosInnerTest {
    private final LiveEventVideosAddMultipleVideosRequestVideosInner model = new LiveEventVideosAddMultipleVideosRequestVideosInner();

    /**
     * Model tests for LiveEventVideosAddMultipleVideosRequestVideosInner
     */
    @Test
    public void testLiveEventVideosAddMultipleVideosRequestVideosInner() {
        // TODO: test LiveEventVideosAddMultipleVideosRequestVideosInner
    }

    /**
     * Test the property 'video'
     */
    @Test
    public void videoTest() {
        // TODO: test video
    }

}
