/*
 * Vimeo API
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OnDemandEssentialsCreatePageRequestEpisodesRentPrice
 */
public class OnDemandEssentialsCreatePageRequestEpisodesRentPriceTest {
    private final OnDemandEssentialsCreatePageRequestEpisodesRentPrice model = new OnDemandEssentialsCreatePageRequestEpisodesRentPrice();

    /**
     * Model tests for OnDemandEssentialsCreatePageRequestEpisodesRentPrice
     */
    @Test
    public void testOnDemandEssentialsCreatePageRequestEpisodesRentPrice() {
        // TODO: test OnDemandEssentialsCreatePageRequestEpisodesRentPrice
    }

    /**
     * Test the property 'USD'
     */
    @Test
    public void USDTest() {
        // TODO: test USD
    }

}
