/*
 * Vimeo API
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.User;
import com.konfigthis.client.model.Video;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UploadAttempt
 */
public class UploadAttemptTest {
    private final UploadAttempt model = new UploadAttempt();

    /**
     * Model tests for UploadAttempt
     */
    @Test
    public void testUploadAttempt() {
        // TODO: test UploadAttempt
    }

    /**
     * Test the property 'clip'
     */
    @Test
    public void clipTest() {
        // TODO: test clip
    }

    /**
     * Test the property 'form'
     */
    @Test
    public void formTest() {
        // TODO: test form
    }

    /**
     * Test the property 'ticketId'
     */
    @Test
    public void ticketIdTest() {
        // TODO: test ticketId
    }

    /**
     * Test the property 'uploadLink'
     */
    @Test
    public void uploadLinkTest() {
        // TODO: test uploadLink
    }

    /**
     * Test the property 'uri'
     */
    @Test
    public void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
