/*
 * Vimeo API
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VideoMetadataInteractionsAlbum;
import com.konfigthis.client.model.VideoMetadataInteractionsAskAi;
import com.konfigthis.client.model.VideoMetadataInteractionsAskAiViewer;
import com.konfigthis.client.model.VideoMetadataInteractionsBuy;
import com.konfigthis.client.model.VideoMetadataInteractionsCanRequestTeamRoleUpgrade;
import com.konfigthis.client.model.VideoMetadataInteractionsCanUpdatePrivacyToPublic;
import com.konfigthis.client.model.VideoMetadataInteractionsChannel;
import com.konfigthis.client.model.VideoMetadataInteractionsCreateEditor;
import com.konfigthis.client.model.VideoMetadataInteractionsDelete;
import com.konfigthis.client.model.VideoMetadataInteractionsEdit;
import com.konfigthis.client.model.VideoMetadataInteractionsEditPrivacy;
import com.konfigthis.client.model.VideoMetadataInteractionsHasRestrictedPrivacyOptions;
import com.konfigthis.client.model.VideoMetadataInteractionsHighlights;
import com.konfigthis.client.model.VideoMetadataInteractionsInvite;
import com.konfigthis.client.model.VideoMetadataInteractionsLegalHold;
import com.konfigthis.client.model.VideoMetadataInteractionsLike;
import com.konfigthis.client.model.VideoMetadataInteractionsRent;
import com.konfigthis.client.model.VideoMetadataInteractionsReport;
import com.konfigthis.client.model.VideoMetadataInteractionsSetContentRating;
import com.konfigthis.client.model.VideoMetadataInteractionsSubscribe;
import com.konfigthis.client.model.VideoMetadataInteractionsSummary;
import com.konfigthis.client.model.VideoMetadataInteractionsTeamMentions;
import com.konfigthis.client.model.VideoMetadataInteractionsTranscriptVideoEditor;
import com.konfigthis.client.model.VideoMetadataInteractionsTrim;
import com.konfigthis.client.model.VideoMetadataInteractionsValidate;
import com.konfigthis.client.model.VideoMetadataInteractionsViewPrivacy;
import com.konfigthis.client.model.VideoMetadataInteractionsViewTeamMembers;
import com.konfigthis.client.model.VideoMetadataInteractionsWatched;
import com.konfigthis.client.model.VideoMetadataInteractionsWatchlater;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VideoMetadataInteractions
 */
public class VideoMetadataInteractionsTest {
    private final VideoMetadataInteractions model = new VideoMetadataInteractions();

    /**
     * Model tests for VideoMetadataInteractions
     */
    @Test
    public void testVideoMetadataInteractions() {
        // TODO: test VideoMetadataInteractions
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'album'
     */
    @Test
    public void albumTest() {
        // TODO: test album
    }

    /**
     * Test the property 'askAi'
     */
    @Test
    public void askAiTest() {
        // TODO: test askAi
    }

    /**
     * Test the property 'askAiViewer'
     */
    @Test
    public void askAiViewerTest() {
        // TODO: test askAiViewer
    }

    /**
     * Test the property 'buy'
     */
    @Test
    public void buyTest() {
        // TODO: test buy
    }

    /**
     * Test the property 'canRequestTeamRoleUpgrade'
     */
    @Test
    public void canRequestTeamRoleUpgradeTest() {
        // TODO: test canRequestTeamRoleUpgrade
    }

    /**
     * Test the property 'canUpdatePrivacyToPublic'
     */
    @Test
    public void canUpdatePrivacyToPublicTest() {
        // TODO: test canUpdatePrivacyToPublic
    }

    /**
     * Test the property 'channel'
     */
    @Test
    public void channelTest() {
        // TODO: test channel
    }

    /**
     * Test the property 'createEditor'
     */
    @Test
    public void createEditorTest() {
        // TODO: test createEditor
    }

    /**
     * Test the property 'delete'
     */
    @Test
    public void deleteTest() {
        // TODO: test delete
    }

    /**
     * Test the property 'edit'
     */
    @Test
    public void editTest() {
        // TODO: test edit
    }

    /**
     * Test the property 'editPrivacy'
     */
    @Test
    public void editPrivacyTest() {
        // TODO: test editPrivacy
    }

    /**
     * Test the property 'hasRestrictedPrivacyOptions'
     */
    @Test
    public void hasRestrictedPrivacyOptionsTest() {
        // TODO: test hasRestrictedPrivacyOptions
    }

    /**
     * Test the property 'highlights'
     */
    @Test
    public void highlightsTest() {
        // TODO: test highlights
    }

    /**
     * Test the property 'invite'
     */
    @Test
    public void inviteTest() {
        // TODO: test invite
    }

    /**
     * Test the property 'legalHold'
     */
    @Test
    public void legalHoldTest() {
        // TODO: test legalHold
    }

    /**
     * Test the property 'like'
     */
    @Test
    public void likeTest() {
        // TODO: test like
    }

    /**
     * Test the property 'rent'
     */
    @Test
    public void rentTest() {
        // TODO: test rent
    }

    /**
     * Test the property 'report'
     */
    @Test
    public void reportTest() {
        // TODO: test report
    }

    /**
     * Test the property 'setContentRating'
     */
    @Test
    public void setContentRatingTest() {
        // TODO: test setContentRating
    }

    /**
     * Test the property 'subscribe'
     */
    @Test
    public void subscribeTest() {
        // TODO: test subscribe
    }

    /**
     * Test the property 'teamMentions'
     */
    @Test
    public void teamMentionsTest() {
        // TODO: test teamMentions
    }

    /**
     * Test the property 'transcriptVideoEditor'
     */
    @Test
    public void transcriptVideoEditorTest() {
        // TODO: test transcriptVideoEditor
    }

    /**
     * Test the property 'trim'
     */
    @Test
    public void trimTest() {
        // TODO: test trim
    }

    /**
     * Test the property 'validate'
     */
    @Test
    public void validateTest() {
        // TODO: test validate
    }

    /**
     * Test the property 'viewPrivacy'
     */
    @Test
    public void viewPrivacyTest() {
        // TODO: test viewPrivacy
    }

    /**
     * Test the property 'viewTeamMembers'
     */
    @Test
    public void viewTeamMembersTest() {
        // TODO: test viewTeamMembers
    }

    /**
     * Test the property 'watched'
     */
    @Test
    public void watchedTest() {
        // TODO: test watched
    }

    /**
     * Test the property 'watchlater'
     */
    @Test
    public void watchlaterTest() {
        // TODO: test watchlater
    }

}
