/*
 * Vimeo API
 * Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.
 *
 * The version of the OpenAPI document: 3.4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * A standard connection object indicating how to get the owner of this user.
 */
@ApiModel(description = "A standard connection object indicating how to get the owner of this user.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TeamMembershipMetadataConnectionsOwner {
  public static final String SERIALIZED_NAME_DISPLAY_NAME = "display_name";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_INVITES_REMAINING = "invites_remaining";
  @SerializedName(SERIALIZED_NAME_INVITES_REMAINING)
  private Double invitesRemaining;

  public static final String SERIALIZED_NAME_OPTIONS = "options";
  @SerializedName(SERIALIZED_NAME_OPTIONS)
  private List<String> options = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Double total;

  public static final String SERIALIZED_NAME_TOTAL_MEMBERS = "total_members";
  @SerializedName(SERIALIZED_NAME_TOTAL_MEMBERS)
  private Double totalMembers;

  public static final String SERIALIZED_NAME_URI = "uri";
  @SerializedName(SERIALIZED_NAME_URI)
  private String uri;

  public TeamMembershipMetadataConnectionsOwner() {
  }

  public TeamMembershipMetadataConnectionsOwner displayName(String displayName) {
    
    
    
    
    this.displayName = displayName;
    return this;
  }

   /**
   * The display name of the team owner.
   * @return displayName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Example Team Name", required = true, value = "The display name of the team owner.")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    
    
    
    this.displayName = displayName;
  }


  public TeamMembershipMetadataConnectionsOwner email(String email) {
    
    
    
    
    this.email = email;
    return this;
  }

   /**
   * The team owner&#39;s email address.
   * @return email
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "user@example.com", required = true, value = "The team owner's email address.")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    
    
    
    this.email = email;
  }


  public TeamMembershipMetadataConnectionsOwner invitesRemaining(Double invitesRemaining) {
    
    
    
    
    this.invitesRemaining = invitesRemaining;
    return this;
  }

  public TeamMembershipMetadataConnectionsOwner invitesRemaining(Integer invitesRemaining) {
    
    
    
    
    this.invitesRemaining = invitesRemaining.doubleValue();
    return this;
  }

   /**
   * The total number of remaining team member invites.
   * @return invitesRemaining
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "5", required = true, value = "The total number of remaining team member invites.")

  public Double getInvitesRemaining() {
    return invitesRemaining;
  }


  public void setInvitesRemaining(Double invitesRemaining) {
    
    
    
    this.invitesRemaining = invitesRemaining;
  }


  public TeamMembershipMetadataConnectionsOwner options(List<String> options) {
    
    
    
    
    this.options = options;
    return this;
  }

  public TeamMembershipMetadataConnectionsOwner addOptionsItem(String optionsItem) {
    this.options.add(optionsItem);
    return this;
  }

   /**
   * An array of HTTP methods permitted on this URI.
   * @return options
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "An array of HTTP methods permitted on this URI.")

  public List<String> getOptions() {
    return options;
  }


  public void setOptions(List<String> options) {
    
    
    
    this.options = options;
  }


  public TeamMembershipMetadataConnectionsOwner total(Double total) {
    
    
    
    
    this.total = total;
    return this;
  }

  public TeamMembershipMetadataConnectionsOwner total(Integer total) {
    
    
    
    
    this.total = total.doubleValue();
    return this;
  }

   /**
   * The total number of owners on this connection.
   * @return total
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "The total number of owners on this connection.")

  public Double getTotal() {
    return total;
  }


  public void setTotal(Double total) {
    
    
    
    this.total = total;
  }


  public TeamMembershipMetadataConnectionsOwner totalMembers(Double totalMembers) {
    
    
    
    
    this.totalMembers = totalMembers;
    return this;
  }

  public TeamMembershipMetadataConnectionsOwner totalMembers(Integer totalMembers) {
    
    
    
    
    this.totalMembers = totalMembers.doubleValue();
    return this;
  }

   /**
   * The total number of team members for the specified team owner.
   * @return totalMembers
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "3", required = true, value = "The total number of team members for the specified team owner.")

  public Double getTotalMembers() {
    return totalMembers;
  }


  public void setTotalMembers(Double totalMembers) {
    
    
    
    this.totalMembers = totalMembers;
  }


  public TeamMembershipMetadataConnectionsOwner uri(String uri) {
    
    
    
    
    this.uri = uri;
    return this;
  }

   /**
   * The API URI that resolves to the connection data.
   * @return uri
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "/users/152184", required = true, value = "The API URI that resolves to the connection data.")

  public String getUri() {
    return uri;
  }


  public void setUri(String uri) {
    
    
    
    this.uri = uri;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TeamMembershipMetadataConnectionsOwner instance itself
   */
  public TeamMembershipMetadataConnectionsOwner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamMembershipMetadataConnectionsOwner teamMembershipMetadataConnectionsOwner = (TeamMembershipMetadataConnectionsOwner) o;
    return Objects.equals(this.displayName, teamMembershipMetadataConnectionsOwner.displayName) &&
        Objects.equals(this.email, teamMembershipMetadataConnectionsOwner.email) &&
        Objects.equals(this.invitesRemaining, teamMembershipMetadataConnectionsOwner.invitesRemaining) &&
        Objects.equals(this.options, teamMembershipMetadataConnectionsOwner.options) &&
        Objects.equals(this.total, teamMembershipMetadataConnectionsOwner.total) &&
        Objects.equals(this.totalMembers, teamMembershipMetadataConnectionsOwner.totalMembers) &&
        Objects.equals(this.uri, teamMembershipMetadataConnectionsOwner.uri)&&
        Objects.equals(this.additionalProperties, teamMembershipMetadataConnectionsOwner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, email, invitesRemaining, options, total, totalMembers, uri, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamMembershipMetadataConnectionsOwner {\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    invitesRemaining: ").append(toIndentedString(invitesRemaining)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    totalMembers: ").append(toIndentedString(totalMembers)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("display_name");
    openapiFields.add("email");
    openapiFields.add("invites_remaining");
    openapiFields.add("options");
    openapiFields.add("total");
    openapiFields.add("total_members");
    openapiFields.add("uri");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("display_name");
    openapiRequiredFields.add("email");
    openapiRequiredFields.add("invites_remaining");
    openapiRequiredFields.add("options");
    openapiRequiredFields.add("total");
    openapiRequiredFields.add("total_members");
    openapiRequiredFields.add("uri");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TeamMembershipMetadataConnectionsOwner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TeamMembershipMetadataConnectionsOwner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TeamMembershipMetadataConnectionsOwner is not found in the empty JSON string", TeamMembershipMetadataConnectionsOwner.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TeamMembershipMetadataConnectionsOwner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("display_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `display_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("display_name").toString()));
      }
      if (!jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("options") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("options").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `options` to be an array in the JSON string but got `%s`", jsonObj.get("options").toString()));
      }
      if (!jsonObj.get("uri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uri").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TeamMembershipMetadataConnectionsOwner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TeamMembershipMetadataConnectionsOwner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TeamMembershipMetadataConnectionsOwner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TeamMembershipMetadataConnectionsOwner.class));

       return (TypeAdapter<T>) new TypeAdapter<TeamMembershipMetadataConnectionsOwner>() {
           @Override
           public void write(JsonWriter out, TeamMembershipMetadataConnectionsOwner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TeamMembershipMetadataConnectionsOwner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TeamMembershipMetadataConnectionsOwner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TeamMembershipMetadataConnectionsOwner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TeamMembershipMetadataConnectionsOwner
  * @throws IOException if the JSON string is invalid with respect to TeamMembershipMetadataConnectionsOwner
  */
  public static TeamMembershipMetadataConnectionsOwner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TeamMembershipMetadataConnectionsOwner.class);
  }

 /**
  * Convert an instance of TeamMembershipMetadataConnectionsOwner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

